<?php
/**
 * Created by PhpStorm.
 * User: liu
 * Date: 1/16/17
 * Time: 2:03 PM
 */

namespace app\admin\model;
use think\Model;

class System extends Model{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
    }


}