<?php
/**
 * Created by PhpStorm.
 * User: liu
 * Date: 1/9/17
 * Time: 4:59 PM
 */

namespace app\admin\controller;
use think\Log;
/**
 * @property  admin
 */

class Admin extends AdminBase{
    public $strs = [
        "phone"=>"手机号",
        "account"=>"用户名",
        "email"=>"邮箱",
        "pwd"=>"密码"
    ];
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->admins = model("Admin");
        if($this->needLogin([url('admin/admin/login'),url("admin/admin/check")])){
            $this->setGlobalUser();
        }
    }

    public function index(){
        $this->getMenu();
        $root = array_filter(explode(DIRECTORY_SEPARATOR,ROOT_PATH));
        var_dump($root);
        $root = '/'.$root[(count($root))];
        echo $root;
        return view("admin/index",['path'=>url("/","","",true)]);
    }

//    public function tests(){
//        return view("admin/test");
//    }
    public function admin_group(){
        if($this->request->isPost()){
            $data = model("AdminGroup")->getAll();
            return $data;
        }

        return view("admin/group");
    }

    public function out_sys(){
        session(null);
        $this->redirect(url("admin/admin/login"));
    }

    public function admin_add(){
        if($this->request->isAjax()){
            if(!isset($this->request_data['id'])) {
                $datas = $this->admins->getAccount($this->request_data['account']);
                if (!empty($datas)){
                    return ['error'=>1,"msg"=>'账号已存在'];
                }
            }
            $vali = validate("admin");
            if(isset($this->request_data['id']) && $this->request_data['pwd'] == '') {
                $vali->scene("edit");
            }
            if(!$vali->check($this->request_data)){
                $error = $vali->getError();
                foreach ($this->strs as $k=>$v){
                    if (strstr($error,$k) != ''){
                        return ['el'=> $k,'msg'=> str_replace($k,$v,$error),'error'=> 1];
                    }
                }
            }
            $data = $this->request_data;
            if(isset($this->request_data['id']) && $this->request_data['pwd'] == '') {
                unset($data['pwd']);
            }
            $res = $this->admins->insertAccount($data);
            return ['error'=>0];
        }
        if (isset($this->request_data['id'])) {
            $this->assign("userinfo",model("admin")->getAccountInfo($this->request_data['id']));
            $this->assign("hasid", true);
        }else{
            $this->assign("userinfo",['account'=>'','pwd'=>'','email'=>'','note'=>'','phone'=>'','admin_group'=>1]);
        }
        $this->assign("group",model("AdminGroup")::all());
        return view("admin/admin/add");
    }

    public function admin_edit(){
//        if (){
//            
//        }
        return view("admin/admin/edit");
    }

    public function admin_list(){
        if($this->request->isPost()){
            $data = $this->admins->getJdata(0);
            return $data;
        }
        return view("admin/admin/list");
    }

    public function check(){
        $data = $this->request_data;
        if ($data['isajax'] == 1){
            if (!captcha_check($data['vercode'])){
                return ['ok'=>0,'msg'=>'验证码错误'];
            }else{
                session("check_code",1);
                return ["ok"=>1];
            }

        }else{
            if (!session("check_code")){
                return $this->error("请认真填写",url("admin/admin/login"));
            }
            $account = $this->admins->getAccount($data['account']);
            if (empty($account)){
                return $this->error("用户名或密码错误，请重新输入",url("admin/admin/login"));
            }
            $pwd = md5(md5($data['pwd']).$account['salt']);
            if ($pwd != $account['pwd']){
                return $this->error("用户名或密码错误，请重新输入",url("admin/admin/login"));
            }
            $this->admins->updateAccount($data['pwd'],$account['uid']);
            session("admin_res",['account'=>$data['account'],"uid"=>$account['uid']]);
            $this->success("登录成功",url("admin/admin/index"));
        }
    }

    public function login(){
        if (session("admin_res")){
            $this->redirect(url("admin/admin/index"));
        }
        return view("admin/login");
    }
}