<?php
/**
 * Created by PhpStorm.
 * User: liu
 * Date: 1/17/17
 * Time: 3:32 PM
 */

namespace app\admin\controller;
use think\Controller;

class AdminBase extends Controller{
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        //声明全局数组
        $GLOBALS['admin'] = [];
        $this->request_data = $this->request->param();
    }

    //判断是否登录
    /** @var TYPE_NAME $url */
    public function needLogin($fild = [],$url = ''){
        if ($url == '')
            $url = url("admin/admin/login");
        if (!session("admin_res") && !in_array($this->request->baseUrl(),$fild)){
            $this->redirect($url);
        }else{
            return true;
        }
    }

    public function setGlobalUser(){
        //生成用户信息 全局调用
        $GLOBALS['admin']['user'] = model("Admin")->getAccountInfo(session("admin_res")['uid']);
        if(isset($GLOBALS['admin']['user'])){
            $this->assign("userinfo",$GLOBALS['admin']['user']);
        }else{
            $this->assign("userinfo",'');
        }
    }

    public function getMenu($tid = 1){
        $data = model("menu")->getMenu($tid);
        $this->assign("menu",$data);
    }
}