<?php
namespace app\index\controller;
use think\Route;
use think\Request;
use think\Controller;
class Index extends Controller{
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->data = $this->request->param();
    }

    public function index(){
        //return view("index",["name"=>'1111']);
    }

    public function plugin(){
        $name = ucwords($this->data['name']);
        $controller = empty($this->data['controller'])?'index':$this->data['controller'];
        if (empty($name)){
            echo "请输入插件名称";
        }
        $addone = controller('addones/'.$name,$name);
        $func = "doWeb".ucwords($controller);
        return $addone->$func();
    }
}
